name: Demo macOS Static Runner with Chrome and Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-run:
    runs-on: [self-hosted, macOS]  # Specifies the self-hosted macOS runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Homebrew (if not already installed)
      - name: Install Homebrew
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          else
            echo "Homebrew is already installed"
          fi

      # Step 3: Install Google Chrome via Homebrew
      - name: Install Google Chrome
        run: |
          brew install --cask google-chrome || echo "Google Chrome installation failed or already installed"

      # Step 4: Verify Chrome installation
      - name: Verify Chrome installation
        run: |
          if [ -d "/Applications/Google Chrome.app" ]; then
            echo "Google Chrome is installed"
            /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
          else
            echo "Google Chrome not found"
            exit 1
          fi

      # Step 5: Print Hello World
      - name: Print Hello World
        run: echo "Hello, World!"

      # Step 6: Print environment details
      - name: Print environment details
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "macOS version: $(sw_vers -productVersion)"
