name: Orka Runner Test

on:
  workflow_dispatch:

jobs:
  test-on-orka:
    runs-on: [self-hosted, orka]
    steps:
      - name: Update Homebrew
        run: brew update

      - name: Install htop
        run: brew install htop

      - name: Run htop version
        run: htop --version

